import { useEffect, useRef } from 'react';
import JsBarcode from 'jsbarcode';
import { Button } from '@/components/ui/button';
import { Printer } from 'lucide-react';

interface BarcodeLabelProps {
  jobNumber: string;
  orderNumber?: string;
  clientName?: string;
  dueDate?: string;
  currentStage?: string;
}

export function BarcodeLabel({ jobNumber, orderNumber, clientName, dueDate, currentStage }: BarcodeLabelProps) {
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    if (svgRef.current) {
      JsBarcode(svgRef.current, jobNumber, {
        format: 'CODE128',
        width: 2,
        height: 50,
        displayValue: true,
        fontSize: 14,
        margin: 5,
        background: '#ffffff',
        lineColor: '#000000',
      });
    }
  }, [jobNumber]);

  const handlePrint = () => {
    const printWindow = window.open('', '_blank', 'width=400,height=300');
    if (!printWindow) return;

    const esc = (s: string) =>
      s.replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');

    const safeJobNumber = esc(jobNumber);
    const safeOrderNumber = orderNumber ? esc(orderNumber) : '';
    const safeClientName = clientName ? esc(clientName) : '';
    const safeDueDate = dueDate ? esc(dueDate) : '';
    const safeCurrentStage = currentStage ? esc(currentStage) : '';
    // SVG generated by JsBarcode from jobNumber (CODE128 charset only) — safe to inline
    const barcodeSvg = svgRef.current?.outerHTML || '';

    printWindow.document.write(`
      <html>
        <head>
          <title>Eticheta ${safeJobNumber}</title>
          <style>
            body { margin: 0; padding: 10px; font-family: Arial, sans-serif; text-align: center; }
            .label { border: 1px dashed #ccc; padding: 10px; display: inline-block; }
            .info { font-size: 11px; margin-top: 4px; color: #333; }
            .info strong { font-size: 12px; }
            @media print { .label { border: none; } }
          </style>
        </head>
        <body>
          <div class="label">
            ${barcodeSvg}
            ${safeOrderNumber ? `<div class="info"><strong>Cmd: ${safeOrderNumber}</strong></div>` : ''}
            ${safeClientName ? `<div class="info">${safeClientName}</div>` : ''}
            ${safeDueDate ? `<div class="info">Termen: ${safeDueDate}</div>` : ''}
            ${safeCurrentStage ? `<div class="info">Etapă: ${safeCurrentStage}</div>` : ''}
          </div>
          <script>window.onload = function() { window.print(); window.close(); }</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="flex flex-col items-center gap-3 p-4 border rounded-lg bg-background">
      <div className="bg-white p-2 rounded">
        <svg ref={svgRef} />
      </div>
      <div className="text-center text-sm space-y-0.5">
        {orderNumber && <p className="font-medium">Cmd: {orderNumber}</p>}
        {clientName && <p className="text-muted-foreground">{clientName}</p>}
        {dueDate && <p className="text-xs text-muted-foreground">Termen: {dueDate}</p>}
      </div>
      <Button onClick={handlePrint} variant="outline" size="sm">
        <Printer className="h-4 w-4 mr-2" />
        Printează Eticheta
      </Button>
    </div>
  );
}
