export const HEADER_MAPS: Record<string, Record<string, string>> = {
  clients: {
    name: 'Nume',
    client_type: 'Tip Client',
    company_name: 'Firma',
    email: 'Email',
    phone: 'Telefon',
    address: 'Adresă',
    city: 'Oraș',
    county: 'Județ',
    postal_code: 'Cod Poștal',
    country: 'Țară',
    cui: 'CUI',
    reg_com: 'Reg. Com.',
    discount_percent: 'Discount (%)',
    notes: 'Observații',
  },
  quotes: {
    ref_number: 'Nr. Referință',
    product_type: 'Tip Produs',
    product_label: 'Denumire Produs',
    client_name: 'Client',
    client_phone: 'Telefon Client',
    client_email: 'Email Client',
    total_price: 'Preț Total',
    tva_percent: 'TVA (%)',
    markup_percent: 'Adaos (%)',
    status: 'Status',
    created_at: 'Data Creare',
  },
  orders: {
    order_number: 'Nr. Comandă',
    status: 'Status',
    subtotal: 'Subtotal',
    discount_percent: 'Discount (%)',
    total: 'Total',
    paid_amount: 'Sumă Plătită',
    delivery_date: 'Data Livrare',
    delivery_address: 'Adresă Livrare',
    notes: 'Observații',
    created_at: 'Data Creare',
  },
  materials: {
    code: 'Cod',
    name: 'Nume',
    material_type: 'Tip',
    unit: 'Unitate',
    unit_price: 'Preț Unitar',
    stock_quantity: 'Stoc',
    min_stock_level: 'Stoc Minim',
    supplier: 'Furnizor',
    location: 'Locație',
    is_active: 'Activ',
  },
};

export const TABLE_CONFIGS: Record<string, { cols: string; label: string; filename: string; orderBy: string }> = {
  clients: {
    cols: 'name, client_type, company_name, email, phone, address, city, county, postal_code, country, cui, reg_com, discount_percent, notes',
    label: 'Clienți',
    filename: 'clienti',
    orderBy: 'created_at',
  },
  quotes: {
    cols: 'ref_number, product_type, product_label, client_name, client_phone, client_email, total_price, tva_percent, markup_percent, status, created_at',
    label: 'Oferte',
    filename: 'oferte',
    orderBy: 'created_at',
  },
  orders: {
    cols: 'order_number, status, subtotal, discount_percent, total, paid_amount, delivery_date, delivery_address, notes, created_at',
    label: 'Comenzi',
    filename: 'comenzi',
    orderBy: 'created_at',
  },
  materials: {
    cols: 'code, name, material_type, unit, unit_price, stock_quantity, min_stock_level, supplier, location, is_active',
    label: 'Materiale',
    filename: 'materiale',
    orderBy: 'name',
  },
};
